# Generated by Django 4.2.3 on 2023-07-16 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2023, 7, 23, 19, 39, 41, 947974, tzinfo=datetime.timezone.utc))),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.list')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
